#version 450 core

#extension GL_EXT_debug_printf : enable

layout(local_size_x=16,local_size_y=8,local_size_z=1) in;
layout(std430,binding=0) buffer Buff{
    float valuesA[];
};

layout(std430, binding=1) buffer Buff1{
    float valuesB[];
};

layout(std430, binding=2) buffer Buff2{
    float outValues[];
};

layout(binding=3) uniform Size{
    uint numColumns;
};

void main(){
    uvec3 mynum = gl_GlobalInvocationID;


    uint row = mynum.x;
    uint col = mynum.y;
    if(row >= numColumns || col >= numColumns){
        return;
    }

    float total = 0.0;
    for(uint k=0; k<numColumns; k++){
        total += valuesA[row * numColumns + k] * valuesB[k * numColumns + col];
    }

    outValues[row * numColumns + col] = total;
}
